import type { ReactNode } from "react";
import MarketingChrome from "@/components/MarketingChrome";
import PageMeta from "@/components/PageMeta";
import {
  ADDRESS_MAILING,
  ADDRESS_OPERATING,
  EMAIL_LEGAL,
  formatAddress,
  LEGAL_NAME,
  PHONE,
  PHONE_HREF,
} from "@/lib/company";

function Section({ title, children }: { title: string; children: ReactNode }) {
  return (
    <section className="legal-block">
      <h2>{title}</h2>
      <div className="prose-light">{children}</div>
    </section>
  );
}

export default function TermsOfService() {
  return (
    <MarketingChrome>
      <PageMeta
        title="Terms of Service — AI Tech Pros"
        description="Terms for the AI Tech Pros, Inc. marketing website. Other products publish their own terms."
        path="/terms"
      />
      <main id="main" className="subpage legal-page">
        <header className="subpage-hero">
          <p className="eyebrow">Legal</p>
          <h1>Terms of Service</h1>
          <p>Last updated: August 30, 2026</p>
        </header>

        <Section title="1. Agreement">
          <p>
            By using this marketing website of {LEGAL_NAME} (&quot;AI Tech Pros,&quot; &quot;we,&quot; &quot;us&quot;), including aitechpros.ai, you agree to these Terms. {LEGAL_NAME} is a Georgia corporation, not an LLC. If you use this site for an organization, you represent that you can bind that organization.
          </p>
        </Section>

        <Section title="2. What this site is">
          <p>This website provides company information, venture links, academy and backoffice explanations, and a conversation booking page. It is not a product login.</p>
          <p>Separate terms apply to OrchestrateOS, MedStore Inc. healthcare offerings, Negotiate Medical Bill, educator backoffice contracts, and the Henry Jenkins Mentorship community on Skool.</p>
        </Section>

        <Section title="3. Eligibility">
          <p>You must be at least 18 and able to form a contract. Healthcare and enterprise products may require additional agreements. Education pages do not replace professional or legal advice.</p>
        </Section>

        <Section title="4. Accounts">
          <p>This marketing site does not create product accounts. If you later receive credentials for OrchestrateOS or another AI Tech Pros product, those credentials are governed by that product&apos;s terms.</p>
        </Section>

        <Section title="5. Education and community">
          <p>
            Academy content is for learning. We do not guarantee certification results, employment, interviews, or salary. Free study materials described on this site remain available without purchasing community membership. Optional Career Ops or coaching is a separate, disclosed offer.
          </p>
        </Section>

        <Section title="6. Healthcare and AI outputs">
          <p>
            Links from this site to MedStore Inc. or Negotiate Medical Bill do not make this page a healthcare service. Those products may process sensitive data under HIPAA and their own terms. Anything generated by AI can be wrong. You are responsible for reviewing outputs before acting.
          </p>
        </Section>

        <Section title="7. Acceptable use">
          <p>You may not use this website to violate law, infringe rights, distribute malware, probe systems without authorization, or submit exam-dump or stolen assessment content.</p>
        </Section>

        <Section title="8. Intellectual property">
          <p>
            We and our licensors own this website, branding, and on-page copy. You retain rights in messages you send. You grant us a limited license to receive and process those messages so we can respond. Educators keep their channel IP as described in their member agreement.
          </p>
        </Section>

        <Section title="9. Payment">
          <p>This website does not charge a fee to read or to request a conversation. Paid work is billed under a separate order form or checkout. This site does not process educator payouts or card payments.</p>
        </Section>

        <Section title="10. Disclaimers and liability">
          <p>
            THIS WEBSITE IS PROVIDED &quot;AS IS.&quot; TO THE MAXIMUM EXTENT PERMITTED BY LAW, {LEGAL_NAME} IS NOT LIABLE FOR INDIRECT, INCIDENTAL, SPECIAL, CONSEQUENTIAL, OR PUNITIVE DAMAGES, OR LOST PROFITS, DATA, OR BUSINESS. OUR TOTAL LIABILITY FOR CLAIMS UNDER THESE TERMS WILL NOT EXCEED THE AMOUNT YOU PAID US FOR WORK RELATED TO THIS SITE IN THE TWELVE MONTHS BEFORE THE CLAIM, OR ONE HUNDRED U.S. DOLLARS IF YOU PAID NOTHING.
          </p>
        </Section>

        <Section title="11. Indemnity">
          <p>You will indemnify {LEGAL_NAME}, MedStore Inc., and our officers, including the CEO and CTO, from claims arising from your use of this website or violation of these Terms.</p>
        </Section>

        <Section title="12. Termination">
          <p>We may suspend or block access to this website for violation of these Terms or with reasonable notice. Provisions that should survive (including IP, disclaimers, and liability limits) remain in effect.</p>
        </Section>

        <Section title="13. Governing law">
          <p>
            These Terms are governed by the laws of the State of Georgia, United States, without regard to conflict-of-law rules. Courts in Augusta, Georgia have exclusive jurisdiction, except where a healthcare or enterprise agreement specifies otherwise.
          </p>
        </Section>

        <Section title="14. Changes">
          <p>We may update these Terms by posting a new version. Continued use after the update is acceptance.</p>
        </Section>

        <Section title="15. Contact">
          <p>
            {LEGAL_NAME}
            <br />
            Operating: {formatAddress(ADDRESS_OPERATING)}
            <br />
            Mailing (MedStore Inc.): {formatAddress(ADDRESS_MAILING)}
            <br />
            Email: <a href={`mailto:${EMAIL_LEGAL}`}>{EMAIL_LEGAL}</a>
            <br />
            Phone: <a href={PHONE_HREF}>{PHONE}</a>
          </p>
        </Section>
      </main>
    </MarketingChrome>
  );
}
